//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5420
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasila.Common {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReceiveInfoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReceiveInfoResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sasila.Common.ReceiveInfoResource", typeof(ReceiveInfoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 青菱乡
        ///九峰乡
        ///建设乡
        ///天兴乡
        ///消泗乡
        ///山坡乡
        ///舒安乡
        ///蔡店乡
        ///木兰乡
        ///名山乡
        ///尹集乡
        ///袁冲乡
        ///茅塔乡
        ///鸳鸯乡
        ///西沟乡
        ///方滩乡
        ///土台乡
        ///五峰乡
        ///大柳乡
        ///安家乡
        ///香口乡
        ///关防乡
        ///景阳乡
        ///六郎乡
        ///涧池乡
        ///湖北口回族乡
        ///潘口乡
        ///竹坪乡
        ///大庙乡
        ///双台乡
        ///楼台乡
        ///文峰乡
        ///深河乡
        ///柳林乡
        ///龙坝乡
        ///新洲乡
        ///兵营乡
        ///鄂坪乡
        ///汇湾乡
        ///天宝乡
        ///桃源乡
        ///窑淮乡
        ///榔口乡
        ///红塔乡
        ///白鹤乡
        ///桥上乡
        ///沙河乡
        ///万峪河乡
        ///九道乡
        ///上龛乡
        ///中坝乡
        ///柘木乡
        ///马家寨乡
        ///窑湾乡
        ///伍家乡
        ///联棚乡
        ///土城乡
        ///下堡坪乡
        ///黄花乡
        ///邓村乡
        ///姚家店乡
        ///五眼泉乡
        ///王家畈乡
        ///潘家湾土家族乡
        ///河口乡
        ///高桥乡
        ///榛子乡
        ///水田坝乡
        ///泄滩乡
        ///梅家河乡
        ///磨坪乡
        ///周坪乡
        ///大堰乡
        ///鸭子口乡
        ///大烧坪乡
        ///采花乡
        ///傅家堰乡
        ///九里回族乡
        ///沙窝乡
        ///临江乡
        ///卧龙乡
        ///朋兴乡
        ///闵集乡
        ///陈店乡
        ///辛榨乡
        ///木梓乡
        ///接官乡
        ///马鞍乡
        ///里潭乡
        ///西江乡
        ///南河乡
        ///湾潭乡
        ///韩集乡
        ///花西乡
        ///季店乡
        ///小悟乡
        ///陡山乡
        ///东新乡
        ///高店 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string countryside {
            get {
                return ResourceManager.GetString("countryside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 世
        ///舜
        ///丞
        ///主
        ///产
        ///仁
        ///仇
        ///仓
        ///仕
        ///仞
        ///任
        ///伋
        ///众
        ///伸
        ///佐
        ///佺
        ///侃
        ///侪
        ///促
        ///俟
        ///信
        ///俣
        ///修
        ///倝
        ///倡
        ///倧
        ///偿
        ///储
        ///僖
        ///僧
        ///僳
        ///儒
        ///俊
        ///伟
        ///列
        ///则
        ///刚
        ///创
        ///前
        ///剑
        ///助
        ///劭
        ///势
        ///勘
        ///参
        ///叔
        ///吏
        ///嗣
        ///士
        ///壮
        ///孺
        ///守
        ///宽
        ///宾
        ///宋
        ///宗
        ///宙
        ///宣
        ///实
        ///宰
        ///尊
        ///峙
        ///峻
        ///崇
        ///崈
        ///川
        ///州
        ///巡
        ///帅
        ///庚
        ///战
        ///才
        ///承
        ///拯
        ///操
        ///斋
        ///昌
        ///晁
        ///暠
        ///曹
        ///曾
        ///珺
        ///玮
        ///珹
        ///琒
        ///琛
        ///琩
        ///琮
        ///琸
        ///瑎
        ///玚
        ///璟
        ///璥
        ///瑜
        ///生
        ///畴
        ///矗
        ///矢
        ///石
        ///磊
        ///砂
        ///碫
        ///示
        ///社
        ///祖
        ///祚
        ///祥
        ///禅
        ///稹
        ///穆
        ///竣
        ///竦
        ///综
        ///缜
        ///绪
        ///舱
        ///舷
        ///船
        ///蚩
        ///襦
        ///轼
        ///辑
        ///轩
        ///子
        ///杰
        ///榜
        ///碧
        ///葆
        ///莱
        ///蒲
        ///天
        ///乐
        ///东
        ///钢
        ///铎
        ///铖
        ///铠
        ///铸
        ///铿
        ///锋
        ///镇
        ///键
        ///镰
        ///馗
        ///旭
        ///骏
        ///骢
        ///骥
        ///驹
        ///驾
        ///骄
        ///诚
        ///诤
        ///赐
        ///慕
        ///端
        ///征
        ///坚
        ///建
        ///弓
        ///强
        ///彦
        ///御
        ///悍
        ///擎
        ///攀
        ///旷
        ///昂
        ///晷
        ///健
        ///冀        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上海街道
        ///大智街道
        ///一元街道
        ///车站街道
        ///四唯街道
        ///永清街道
        ///西马街道
        ///球场街道
        ///劳动街道
        ///二七街道
        ///新村街道
        ///丹水池街道
        ///台北街道
        ///花桥街道
        ///谌家矶街道
        ///后湖街道
        ///民族街道
        ///花楼街道
        ///水塔街道
        ///民权街道
        ///满春街道
        ///民意街道
        ///新华街道
        ///万松街道
        ///唐家墩街道
        ///北湖街道
        ///前进街道
        ///常青街道
        ///汉兴街道
        ///易家墩街道
        ///韩家墩街道
        ///宗关街道
        ///汉水桥街道
        ///宝丰街道
        ///荣华街道
        ///崇仁街道
        ///汉中街道
        ///汉正街街道
        ///六角亭街道
        ///翠微街道
        ///建桥街道
        ///月湖街道
        ///晴川街道
        ///鹦鹉街道
        ///洲头街道
        ///五里墩街道
        ///琴断口街道
        ///江汉二桥街道
        ///永丰街道
        ///江堤街道
        ///积玉桥街道
        ///杨园街道
        ///徐家棚街道
        ///粮道街街道
        ///中华路街道
        ///黄鹤楼街道
        ///紫阳街道
        ///白沙洲街道
        ///首义路街道
        ///中南路街道
        ///水果湖街道
        ///珞珈山街道
        ///石洞街道
        ///红卫路街道
        ///冶金街道
        ///新沟桥街道
        ///红钢城街道
        ///工人村街道
        ///厂前街道
        ///武东街道
        ///白玉山街道
        ///钢花村街道
        ///珞南街道
        ///关山街道
        ///狮子山街道
        ///张家湾街道
        ///红旗街道
        ///葛化街道
        ///洪山街道
        ///和平街道
        ///吴家 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string street {
            get {
                return ResourceManager.GetString("street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 赵
        ///钱
        ///孙
        ///李
        ///周
        ///吴
        ///郑
        ///王
        ///冯
        ///陈
        ///褚
        ///卫
        ///蒋
        ///沈
        ///韩
        ///杨
        ///朱
        ///秦
        ///尤
        ///许
        ///何
        ///吕
        ///施
        ///张
        ///孔
        ///曹
        ///严
        ///华
        ///金
        ///魏
        ///陶
        ///姜
        ///戚
        ///谢
        ///邹
        ///喻
        ///柏
        ///水
        ///窦
        ///章
        ///云
        ///苏
        ///潘
        ///葛
        ///奚
        ///范
        ///彭
        ///郎
        ///鲁
        ///韦
        ///昌
        ///马
        ///苗
        ///凤
        ///花
        ///方
        ///俞
        ///任
        ///袁
        ///柳
        ///酆
        ///鲍
        ///史
        ///唐
        ///费
        ///廉
        ///岑
        ///薛
        ///雷
        ///贺
        ///倪
        ///汤
        ///滕
        ///殷
        ///罗
        ///毕
        ///郝
        ///邬
        ///安
        ///常
        ///乐
        ///于
        ///时
        ///傅
        ///皮
        ///卞
        ///齐
        ///康
        ///伍
        ///余
        ///元
        ///卜
        ///顾
        ///孟
        ///平
        ///黄
        ///和
        ///穆
        ///萧
        ///尹
        ///姚
        ///邵
        ///湛
        ///汪
        ///祁
        ///毛
        ///禹
        ///狄
        ///米
        ///贝
        ///明
        ///臧
        ///计
        ///伏
        ///成
        ///戴
        ///谈
        ///宋
        ///茅
        ///庞
        ///熊
        ///纪
        ///舒
        ///屈
        ///项
        ///祝
        ///董
        ///梁
        ///杜
        ///阮
        ///蓝
        ///闵
        ///席
        ///季
        ///麻
        ///强
        ///贾
        ///路
        ///娄
        ///危
        ///江
        ///童
        ///颜
        ///郭
        ///梅
        ///盛
        ///林
        ///刁
        ///锺
        ///徐
        ///邱
        ///骆
        ///高
        ///夏
        ///蔡
        ///田
        ///樊
        ///胡
        ///凌
        ///霍
        ///虞
        ///万
        ///支
        ///柯
        ///昝
        ///管
        ///卢
        ///莫
        ///经
        ///房
        ///裘        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string surname {
            get {
                return ResourceManager.GetString("surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 青山镇
        ///花山镇
        ///左岭镇
        ///索河镇
        ///玉贤镇
        ///法泗镇
        ///安山镇
        ///湖泗镇
        ///豹澥镇
        ///姚家集镇
        ///蔡家榨镇
        ///王家河镇
        ///李家集镇
        ///长轩岭镇
        ///三里镇
        ///辛冲镇
        ///徐古镇
        ///河口镇
        ///金牛镇
        ///保安镇
        ///灵乡镇
        ///金山店镇
        ///还地桥镇
        ///殷祖镇
        ///汪仁镇
        ///刘仁八镇
        ///陈贵镇
        ///大箕铺镇
        ///兴国镇
        ///富池镇
        ///黄颡口镇
        ///韦源口镇
        ///太子镇
        ///大王镇
        ///陶港镇
        ///白沙镇
        ///浮屠镇
        ///三溪镇
        ///王英镇
        ///龙港镇
        ///洋港镇
        ///木港镇
        ///卧龙镇
        ///欧庙镇
        ///太平店镇
        ///牛首镇
        ///团山镇
        ///张湾镇
        ///龙王镇
        ///石桥镇
        ///黄集镇
        ///伙牌镇
        ///古驿镇
        ///朱集镇
        ///程河镇
        ///双沟镇
        ///张家集镇
        ///黄龙镇
        ///峪山镇
        ///东津镇
        ///米庄镇
        ///孟楼镇
        ///薛集镇
        ///张集镇
        ///仙人渡镇
        ///竹林桥镇
        ///杨垱镇
        ///七方镇
        ///太平镇
        ///鹿头镇
        ///刘升镇
        ///吴店镇
        ///熊集镇
        ///王城镇
        ///兴隆镇
        ///琚湾镇
        ///平林镇
        ///流水镇
        ///板桥店镇
        ///小河镇
        ///刘猴镇
        ///郑集镇
        ///孔湾镇
        ///王集镇
        ///城关镇
        ///武安镇
        ///九集镇
        ///肖堰镇
        ///东巩镇
        ///巡检镇
        ///板桥镇
        ///薛坪镇
        ///长坪镇
        ///城关镇
        ///石花镇
        ///盛康镇
        ///冷集镇
        ///庙滩镇
        ///五山镇
        ///紫 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string town {
            get {
                return ResourceManager.GetString("town", resourceCulture);
            }
        }
    }
}
